version: '3.1'

services:

  mongo:
    image: mongo:5.0.14
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
        - ../data:/data/db
